version: '3.8'

services:
  nestjs:
    container_name: ${PROJECT_NAME}_nestjs
    image: nestjs/nestjs
    build:
      context: .
      dockerfile: ./Dockerfile_nestjs_dev
    environment:
      - NESTJS_APPLICATION_PORT=${NESTJS_APPLICATION_PORT}
      - EDGE_PORT=${EDGE_PORT}
      - EDGE_USER=${EDGE_USER}
      - EDGE_HOST=${EDGE_HOST}
      - EDGE_DB=${EDGE_DB}
    depends_on:
      - edgedb
    ports:
      - ${NESTJS_APPLICATION_PORT}:${NESTJS_APPLICATION_PORT}
      - ${NESTJS_DEBUGGING_PORT}:${NESTJS_DEBUGGING_PORT}
    volumes:
      - ./server:/usr/src/app/
    labels:
      - traefik.http.routers.nestjs.rule=Host(`nestjs.docker.localhost`)
      - traefik.http.services.nestjs.loadbalancer.server.port=${NESTJS_APPLICATION_PORT}
  edgedb:
    container_name: ${PROJECT_NAME}_edgedb
    image: edgedb/edgedb
    hostname: ${EDGE_HOST}
    environment:
      - EDGEDB_SERVER_SECURITY=insecure_dev_mode
    ports:
      - ${EDGE_PORT}:${EDGE_PORT} 
    volumes:
      - ./server/dbschema:/dbschema
      - ./server/edgedb.toml:/edgedb.toml
      - ./server/credentials:/root/.config/edgedb/credentials
  react:
    container_name: ${PROJECT_NAME}_react
    image: react/react
    build:
      context: .
      dockerfile: ./Dockerfile_react_dev
    environment:
      - PORT=${REACT_PORT}
    depends_on:
      - nestjs
    ports:
      - ${REACT_PORT}:${REACT_PORT}
    volumes:
      - ./client:/usr/src/app/
    labels:
      - traefik.http.routers.react.rule=Host(`react.docker.localhost`)
      - traefik.http.services.react.loadbalancer.server.port=${REACT_PORT}
  reverse-proxy:
    image: traefik:v2.6
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
#      - 8080:8080 Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
  # prod:
  #   container_name: ${PROJECT_NAME}_nestjs-prod
  #   image: nestjs-api-prod:1.0.0
  #   build:
  #     context: .
  #     target: production
  #     dockerfile: ./Dockerfile
  #   command: npm run start:prod
  #   ports:
  #     - ${APPLICATION_PORT}:${APPLICATION_PORT}
  #     - ${DEBUGGING_PORT}:${DEBUGGING_PORT}
  #   networks:
  #     - nesjs-network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped