version: '3.8'

services:
  nestjs:
    container_name: ${PROJECT_NAME}_nestjs
    image: nestjs/nestjs
    build:
      context: .
      dockerfile: ./Dockerfile_nestjs_dev
    depends_on:
      - edgedb
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
      - ${DEBUGGING_PORT}:${DEBUGGING_PORT}
    volumes:
      - ./server:/usr/src/app/
  edgedb:
    container_name: ${PROJECT_NAME}_edgedb
    image: edgedb/edgedb
    hostname: edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./server/dbschema:/dbschema"
      - "./server/edgedb.toml:/edgedb.toml"
      - "./server/credentials:/root/.config/edgedb/credentials"
    ports:
      - "5656:5656"    
  # prod:
  #   container_name: ${PROJECT_NAME}_nestjs-prod
  #   image: nestjs-api-prod:1.0.0
  #   build:
  #     context: .
  #     target: production
  #     dockerfile: ./Dockerfile
  #   command: npm run start:prod
  #   ports:
  #     - ${APPLICATION_PORT}:${APPLICATION_PORT}
  #     - ${DEBUGGING_PORT}:${DEBUGGING_PORT}
  #   networks:
  #     - nesjs-network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped